#!/bin/bash

log_dir="$1"
archive_dir="log-archives"

mkdir -p "$archive_dir"

timestamp=$(date +"%Y%m%d_%H%M%S")
#echo "$timestamp"

tar -czvf "$archive_dir/logs_archive_$timestamp.tar.gz" "$log_dir"
